export { default as Home} from './pages/Home'
export { default as Explore} from './pages/Explore'
export { default as Friends} from './pages/Friends'
export { default as Saved} from './pages/Saved'
export { default as CreatePost} from './pages/CreatePost'